# Dependencies
markdown:         kramdown
highlighter:      rouge  # Github pages do not support pygments and only support rouge
syntax_highlighter_opts:
  block:
    line_numbers: true
# highlighter:      pygments
plugins: [jekyll-paginate, jekyll-gist, github-pages]
# Permalinks
permalink:        pretty


# Setup
title:            Robin's Blog
tagline:          'the accounting bird'
description: >- # this means to ignore newlines until "baseurl:"
  This is the Rotki blog at which Robin, the accounting bird, is writing about finance, accounting, analytics, DeFi, cryptoeconomics and more!
twitter_username: rotkiapp
github_username:  rotkehlchenio

url:              https://blog.rotki.com
baseurl:          ""

author:
  name:           'Lefteris Karapetsas'
  url:            https://twitter.com/lefterisjp

paginate:         3


github:
  repo:           https://github.com/rotkehlchenio/rotkehlchen
